// Code generated by kaitai-struct-compiler? Metadata: version 0.10. DO NOT EDIT.

package main

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type BossHeader struct {
	Magic uint32
	Version uint32
	FileSize uint32
	Serial uint64
	Const uint16
	Padding uint16
	Hash uint16
	Rsa uint16
	Iv []byte
	_io *kaitai.Stream
	_root *BossHeader
	_parent interface{}
}

func NewBossHeader() *BossHeader {
	return &BossHeader{
	}
}

func (this *BossHeader) Read(io *kaitai.Stream, parent interface{}, root *BossHeader) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Magic = tmp1
	tmp2, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Version = tmp2
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FileSize = tmp3
	tmp4, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.Serial = tmp4
	tmp5, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Const = tmp5
	tmp6, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Padding = tmp6
	tmp7, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Hash = tmp7
	tmp8, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Rsa = tmp8
	tmp9, err := this._io.ReadBytes(int(12))
	if err != nil {
		return err
	}
	tmp9 = tmp9
	this.Iv = tmp9
	return nil
}
